export const MUTATE_BUNDLE_LIST = "MUTATE_BUNDLE_LIST";
export const MUTATE_CARD_LIST = "MUTATE_CARD_LIST";
export const MUTATE_RECIPIENT = "MUTATE_RECIPIENT";
export const MUTATE_SELECTED_BUNDLE = "MUTATE_SELECTED_BUNDLE";
export const MUTATE_SELECTED_CARD = "MUTATE_SELECTED_CARD";
export const MUTATE_ORDER = "MUTATE_ORDER";

export const MUTATE_CURRENT_STEP = "MUTATE_CURRENT_STEP";
export const MUTATE_ACTIVE_STEP = "MUTATE_ACTIVE_STEP";
export const MUTATE_EVENT = "MUTATE_EVENT";
export const MUTATE_EVENT_ITEMS_LIST = "MUTATE_EVENT_ITEMS_LIST";
export const MUTATE_SAVE_EVENT_ITEMS_LIST = "MUTATE_SAVE_EVENT_ITEMS_LIST";

export const MUTATE_CHANGE_THEME = "MUTATE_CHANGE_THEME";
export const MUTATE_CHANGE_INNERHEIGHT = "MUTATE_CHANGE_INNERHEIGHT";
export const MUTATE_SAVE_CODE = "MUTATE_SAVE_CODE";
export const MUTATE_GENERATE_UUID = "MUTATE_GENERATE_UUID";