export const MUTATE_CLASS_LIST = "MUTATE_CLASS_LIST";
export const MUTATE_DEVICE_LIST = "MUTATE_DEVICE_LIST";
export const MUTATE_DEVICE_ITEM = "MUTATE_DEVICE_ITEM";
export const MUTATE_ATTR_VALUE_LIST = "MUTATE_ATTR_VALUE_LIST";